#!/bin/expect -f
source ./ok.conf
set timeout -1
proc slurp {file} {
    set fh [open $file r]
    set ret [read $fh]
    close $fh
    return $ret
}
log_user 0
set passwd [slurp $credfile]
spawn donkeyrunner $argv > /tmp/screen-exchange
expect "Enter passphrase : "
send -- "$passwd\r"
expect EOF

