#!/bin/expect -f
set timeout -1
log_user 0
proc slurp {file} {
    set fh [open $file r]
    set ret [read $fh]
    close $fh
    return $ret
}
set passwd [slurp /home/dfoulks/.dfoulks.cred]

spawn donkeyrunner $argv
expect "Enter passphrase : "
send -- "$passwd\r"

log_user 1
expect -re "(.*)\r"

#log_user 0
set outcome $expect_out(1,string)

#log_user 1
#puts $outcome
puts [open "/tmp/screen-exchange" "a+"] $outcome

#spawn screen -X readbuf /tmp/screen-exchange
#spawn rm /tmp/screen-exchange
expect EOF
